### ISSUE TITLE
Badge link for USA-2017 isn't working

### ISSUE THREAD

**Issue by etdsoft** [toolswatch/blackhat-arsenal-tools#6]
I wasn't able to use the provided URL:

    https://github.com/toolswatch/badges/blob/master/arsenal/2017.svg

![Arsenal](https://github.com/toolswatch/badges/blob/master/arsenal/2017.svg)

Or the RAW version:

    https://raw.githubusercontent.com/toolswatch/badges/master/arsenal/2017.svg

![Arsenal](https://raw.githubusercontent.com/toolswatch/badges/master/arsenal/2017.svg)

So I had to use rawgithub (3rd party):

    https://rawgithub.com/toolswatch/badges/master/arsenal/2017.svg

![Arsenal](https://rawgithub.com/toolswatch/badges/master/arsenal/2017.svg)

More info:

https://stackoverflow.com/questions/13808020/include-an-svg-hosted-on-github-in-markdown

**Comment by toolswatch** [comment]
weird. This one https://github.com/toolswatch/badges/blob/master/arsenal/2017.svg works good
